### ISSUE TITLE
Add Archive Content Menu links does not work

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-archive-pages#4]
on this page: https://sugarmakers.org/master-articles/

You are not able to click to add a new before/after content.

you have to first create a post in the content type before you can edit before/edit content.

<img width="1097" alt="Screen Shot 2021-10-09 at 5 19 17 PM" src="https://user-images.githubusercontent.com/12969150/136674112-fa553e8e-72e4-4007-a670-628b940ebe1d.png">

**Comment by JiveDig** [comment]
What type of archive is that? Category? Main blog? Custom post type or custom taxonomy?

**Comment by dws122** [comment]
Custom Taxonomy

**Comment by JiveDig** [comment]
This works with custom taxonomies now.
